language: node_js

env:
  - NODE_ENV=development
node_js:
  - '5.4'
script:
  - npm run build

notifications:
  slack:
    secure: "E0k4IHU8BfYiHnayarcpn4Q13K/bszVkDjeEv6vpTClfoGH8zE/YumMWBqCwEKiKc04K+qqrCZDiSgOK/xyX2xgY+QYb4SKuXvXZda44fgt0B6ogDBwG8LLIJzrJmEd8hu0+eCbql+oIurmvtgZHkJNcZytJV4tLiSkPXLwmJ+9Alqhr3IxzbdfZC//xMC5BVLVly+zCQGe4335DiyuklQms97u5U1ubj0f7kt3MOepQpaiQlQ4CoujIXVZEEO8FJEBl34Q1FtX8MYdPSE0ClgjJh1S7iLdu8ANwPvJJWs5H4KRzyIDDEQgoLvVdZwHAqEUuX69+rCaoDPp/Efk4oJzuXpu14110UlZQp/an6s0kFp0FnkR5T8fOM1NDi91emDYorJMTZlGsVVc2QjlF+dMhyhses25j0j+VnSmAajJ5j9dWK8TaAITnVSGP9b0assSpAEGCvV0rrYNb5JklDBHdRi+QfzKBTsnuJF4WUkW95TiWH4PBpE/0ty7FM2ygU9RG6SGd17srhyTrIw6AhkG7elaXvzCx/GQNLnLSSENP3uRQewjx+vPfqGUWfxyg6WhabNSvIPvOtrpPupHgv+SYUGWQ881gC8ioSSHQwBYinq/p8fHI+xmh1qr5vQaAoGbO6vnT1sdKuLBZ+/kd4i3S4Ubw1tI19pJIf94jgv0="
